
#
# Copyright (C) 2025 Salvo Giangreco
#
# Licensed under the GNU General Public License, Version 3.0
#

# Platform configuration file for Samsung Exynos 850 devices (exynos850)
TARGET_BOARD_API_LEVEL=31
TARGET_PRODUCT_SHIPPING_API_LEVEL=31

# Partitions - A04s (Exynos 850) Standart Değerleri
TARGET_BOOT_PARTITION_SIZE=67108864
TARGET_DTBO_PARTITION_SIZE=8388608
# A04s'te genellikle vendor_boot yoktur (Legacy Ramdisk kullanılır), 
# ancak script hata vermesin diye minimum değerde tutuyoruz.
TARGET_VENDOR_BOOT_PARTITION_SIZE=0

# Dynamic partitions - Exynos 850 (universal3830) genellikle 'default' kullanır
TARGET_SUPER_GROUP_NAME="default"

# OS - ESSI yerine QSSI kullanmak One UI 7/GSI uyumluluğu için daha iyidir
TARGET_OS_SINGLE_SYSTEM_IMAGE="qssi"
TARGET_OS_BUILD_SYSTEM_EXT_PARTITION=false

# SEC Product Feature - A04s Donanımına Göre Optimize Edildi
TARGET_WLAN_CONFIG_CONNECTION_PERSONALIZATION="0"
TARGET_WLAN_CONFIG_CPU_CSTATE_DISABLE_THRESHOLD="0"
TARGET_WLAN_CONFIG_DATA_ACTIVITY_AFFINITY_BOOSTER_THRESHOLD="0"
TARGET_WLAN_CONFIG_DYNAMIC_SWITCH="0"
TARGET_WLAN_CONFIG_L1SS_DISABLE_THRESHOLD="0"
TARGET_WLAN_SUPPORT_80211AX=false # A04s Wi-Fi 6 desteklemez
TARGET_WLAN_SUPPORT_APE_SERVICE=false
TARGET_WLAN_SUPPORT_LOWLATENCY=false
TARGET_WLAN_SUPPORT_MBO=true
TARGET_WLAN_SUPPORT_MOBILEAP_5G_BASEDON_COUNTRY=false
TARGET_WLAN_SUPPORT_MOBILEAP_6G=false
TARGET_WLAN_SUPPORT_MOBILEAP_DUALAP=false
TARGET_WLAN_SUPPORT_MOBILEAP_OWE=false
TARGET_WLAN_SUPPORT_MOBILEAP_POWER_SAVEMODE=false
TARGET_WLAN_SUPPORT_MOBILEAP_PRIORITIZE_TRAFFIC=false
TARGET_WLAN_SUPPORT_MOBILEAP_WIFISHARING_LITE=true
TARGET_WLAN_SUPPORT_SWITCH_FOR_INDIVIDUAL_APPS=true
TARGET_WLAN_SUPPORT_TWT_CONTROL=false
TARGET_WLAN_SUPPORT_WIFI_TO_CELLULAR=false
